### ISSUE TITLE
Welcome to iOS!

### ISSUE THREAD

**Issue by chelseatroy** [uchicago-mobi/MPCS51030-2019-Spring-Forum#1]
Please leave a comment on this issue!

**Comment by caterpillai** [comment]
First

**Comment by westminsterabi** [comment]
👋 👋 👋 👋

**Comment by blakefleisher** [comment]
my comment!

**Comment by msmarrow** [comment]
hello!

**Comment by landonjmitchell** [comment]
“Make each product the best it can be. Focus on form and materials. What we don't include is as important as what we do include.”
- Jony Ive

**Comment by miranda66** [comment]
Hello World!

**Comment by itlyons** [comment]
This is my comment.

**Comment by wendywang96** [comment]
Nice to meet you.

**Comment by tracesauter** [comment]
Hey everyone,

I'm Trace - joint degree student between Booth and the MPCS program. Looking forward to getting to know each of you over the course of the quarter!

**Comment by jdgarza** [comment]
Hi everyone!
