### ISSUE TITLE
Assignment 3 Instruction Images

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#14]
There seem to be one or two images missing from this week's assignment description. For example, under the heading 'Project Setup', there is a line that says "When you're done, your storyboard should look similar to the image below". Whenever possible, could we get the image(s) added to the description or posted here?  Thanks.

**Comment by chelseatroy** [comment]
Hi Landon! 

Ah, good catch! I'll update the course site now to include those.
