### ISSUE TITLE
MovieTableViewCell

### ISSUE THREAD

**Issue by westminsterabi** [uchicago-mobi/MPCS51030-2019-Spring-Forum#21]
In the write-up, it says 
"
Create a custom UITableViewCell subclass called MovieTableViewCell. Update the prototype cell in each table view controller to use this subclass. Add an image view and two labels to the prototype cells and create the corresponding IBOutlets in MovieTableViewCell.swift.
"

Doesn't this mean that MovieTableViewCell will have six outlets? Isn't that strange, shouldn't it only have three? I'm a little confused about what we're supposed to be doing here. 

Thanks!

**Comment by hbennett766** [comment]
You can hook up multiple storyboard components to a single IBOutlet in code. For example, you have a `UIImageView` in each prototype cell. You also have a `movieImage` IBOutlet (that should be of type `UIImageView`, not `UILabel`) in your `MovieTableViewCell`. You can drag connections from both prototype cell image objects to that same IBOutlet. You'll have 6 objects in storyboard, 2 for each outlet. Does that make sense?

Unrelated: Please descriptively name the labels in your `MovieTableViewCell`! `label1` and `label2` doesn't tell me anything about what those labels are there for. Instead, choose names such as `titleLabel` and `genreLabel`. That tells me, without even running your app, exactly the information I expect to be displayed in those labels. Refer to #9 for more info.

**Comment by westminsterabi** [comment]
Cool, that makes sense. Don't worry, those names are just placeholders. Thanks!

**Comment by hbennett766** [comment]
Gotcha, sounds good!
