### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by westminsterabi** [uchicago-mobi/MPCS51030-2019-Spring-Forum#23]
Hi, 

I'm having some really pernicious problems with layout at the moment. My current code is pushed. For some reason when I try and resolve the autolayout problems that currently exist, it makes everything look bad and makes text overlap. When I leave the warnings, it looks fine. I'm really confused as to what's happening and why it's doing this.

**Comment by hbennett766** [comment]
I’ll check this out this evening. Layout constraints can be tough.

**Comment by westminsterabi** [comment]
It's due at 5:30 :( Thanks anyway

**Comment by westminsterabi** [comment]
(I took an extension on the assignment due yesterday)

**Comment by hbennett766** [comment]
I’m going to email you, closing out the convo here

**Comment by hbennett766** [comment]
@westminsterabi what’s your email? I don’t have the student list handy atm

**Comment by westminsterabi** [comment]
abihunter@uc

**Comment by westminsterabi** [comment]
Thanks!!
