### ISSUE TITLE
Panning, dropping, MVC - Project 4

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#25]
Currently I’m trying to get the pan functionality to work, e.g. recognizing that a piece has been dropped into a square. It’s not working as desired. I suspect that this has something to do with the pieces and squares having different superviews, but I’m not quite sure what to do about it. Trying to remove the square views from the grid view proves difficult, as dragging them anywhere within the grid view frame adds them to that view, and removing them from the frame in the project outline changes their position. 

The brief in-class demonstration also seemed to  show a piece being dragged from its initial position, while also remaining in its initial position, if that makes sense. Not sure what to do about that one, either. 

I’m also struggling to see/implement the overall MVC structure of the game logic/ grid/ view controller, if you have any suggestions or pointers in that regard.

Thanks

**Comment by hbennett766** [comment]
Two great questions. Splitting this into two posts. Check out #26 for the MVC stuff.

**Comment by hbennett766** [comment]
Matching the pan gesture's end position  to the correct square is entirely dependent on understanding how view frames work.

### How View Frames Work

A view's frame is **relative to its superview**. This is very important when considering the x and y origin of a view frame. Let's use this grid as an example (sorry it's a little blurry).

![Tic-Tac-Toe-Grid-Numbers](https://user-images.githubusercontent.com/10427644/56839984-d2804100-684a-11e9-9eeb-0b01b044c367.jpg)

The purple border represents the edge of the phone screen, point (0,0) in the main view's frame. Now, we have a grid view inside the main view, who's origin point, _relative to the main view_, is (100, 150).

When we drag a game piece to square number 1, the origin point of that game piece can be one of two points:

1. (0, 0)
2. (100, 150)

Which one it is is entirely dependent on the game piece's superview. If the game piece is a subview of the grid view, the game piece's origin will be (0, 0). If the game piece is a subview of the main view, the game piece's origin will be (100, 150).

That logic continues for other squares on the board. Let's say we want to drop a piece into square 5. The origin point for the game piece will either be (100, 100) as a subview of the grid, or (200, 250) as a subview of the main view.

It's all a game of **relativity to the superview**.

### Should the Squares be Subviews of the Grid or the Main View?

Up to you! Both are valid approaches.

You can toggle whether the squares are subviews of the grid or of the main view in the left panel of your storyboard. 

<img width="364" alt="Screen Shot 2019-04-26 at 6 03 04 PM" src="https://user-images.githubusercontent.com/10427644/56840523-97cbd800-684d-11e9-8a23-30301dcd79e9.png">

In this hierarchy, the content view contains a `UIStackView` and a `UIView` (MarkerView). That `UIStackView` contains another `UIStackView` and a `UIView`. 

If I wanted the `MarkerView` to be a subview of the `UIStackView`, I could drag its name inside the hierarchy of the stack view. If I wanted the bottom level `UIView` to be a subview of the content view, I could drag its name out into the main level.

If you adjust hierarchy, your layout constraints will most likely need to be redone.

### Handling Comparisons of Game Piece to Squares

When you drag a game piece from its starting point on the board, that game piece will be a subview of the main view. That is our point of reference to keep in mind.

If your squares are subviews of the main view, and not the grid, the point you get from your pan gesture ending will line up 1 to 1 with the point in the square. You can just compare pan gesture x to square x and pan gesture y to square y.

If your squares are subviews of the grid, it's time for some math. The end point you get from the pan gesture will be relative to the main view, while your square frames will be relative to the grid. You'll have to account for that in your comparison. Addition is a good way to go.

xOrigin = xOriginOfGrid + xOriginOFSquare

That addition will get you from the left side of the screen to the grid, the. The grid to the left side of the square.

Ratios would probably also work. Choose your own math adventure!

**Comment by westminsterabi** [comment]
I'm also confused as to how to make a piece remain in its initial position while also being dragged around. Did that ever get answered? @hbennett766

**Comment by hbennett766** [comment]
That's just an illusion. Probably done by instantiating a new game piece in the starting position frame whenever the user begins a pan gesture.

**Comment by westminsterabi** [comment]
Then how do we make sure that the outlet points to the new one?

**Comment by hbennett766** [comment]
Outlets are variables. You can reassign their reference like a normal var.

`xPiece = <new instance of x piece>`

**Comment by westminsterabi** [comment]
Won't there then be problems with being able to pan the old one?

**Comment by hbennett766** [comment]
The pan gesture recognizer, and other properties attached to the original instance of the game piece, won't transfer over to the new game piece you create. You'll have to add a pan gesture recognizer, along with all the view properties (frame, color, image, text, etc) programatically. The whole object has to be made from scratch. Storyboard can't spawn new game pieces for you during runtime. The only thing you update when assigning the outlet to a new instance is the class-level reference.

**Comment by westminsterabi** [comment]
I'm trying to use the copy method to copy the old piece and insert it as a subview and I'm getting "unrecognized selector sent to instance" as an error 

Here's what I do: 
Finish dropping the piece. 
Call piece.copy()
call a method defined in GridView as addNewPiece, which sets the alpha and the coordinates and then calls self.view.addSubview(newlySpawnedPiece)
