### ISSUE TITLE
graduating student deadlines

### ISSUE THREAD

**Issue by jdgarza** [uchicago-mobi/MPCS51030-2019-Spring-Forum#28]
I was just wondering what the final project proposal/due dates are for graduating students?

Apologies if I missed this info somewhere else!

**Comment by chelseatroy** [comment]
Hi! We haven't gone over this yet (we will on Wednesday), but here's the short version:

The final project proposals will be due for all students on the same date: May 8. 
All students will then have three weeks to complete their final project, so it will be due on May 31.

On June 12th, the iOS Development and Advanced iOS Development classes will combine together (probably in our classroom), and students from both classes will get to present their apps. If students wish, I will film their presentation for use in their portfolio or their personal sites. Students will also be welcome, after the quarter is over, to push their final apps to public repos on their own githubs to show to potential employers.

Between May 31 and June 12, Hannah and I will grade the apps and will provide a review, including any suggestions for improvement. Students are welcome to follow up on these improvements prior to the presentation, but they do not affect the final app grade.

**Comment by jdgarza** [comment]
Sounds good, thank you!
