### ISSUE TITLE
Tic Tac Toe Tile Views

### ISSUE THREAD

**Issue by tracesauter** [uchicago-mobi/MPCS51030-2019-Spring-Forum#29]
The assignment mentions making 9 views for the tiles of the tic tac toe board and creating IBOutlets so we can access them.

For those of us who may or may not have goofed on the initial reading of the instructions and created the views programmatically and added them as subviews of the GridView is it ok to keep it that way, or should we go back and create the views in interface builder and add iboutlets to access them?

thanks!

**Comment by hbennett766** [comment]
This is a @chelseatroy question. I do not hold the power to adjust requirements.

**Comment by westminsterabi** [comment]
Relatedly, I am having trouble creating these views in a way that lines up with the squares. I tried embedding three stack views within a larger stack view and selecting "fill equally" but that doesn't appear to...do anything? Everything just stays in the same place.

**Comment by westminsterabi** [comment]
@hbennett766

**Comment by hbennett766** [comment]
Oh hey @westminsterabi sorry, gmail was marking my github emails as spam 🙄

When that happens in a storyboard, it means the constraints aren't fully satisfied. The view doesn't have enough information to lay everything out. You can use stack views here, but you'll have to, along with telling them all to fill equally, give them constraints pinning the larger stack view to x points from each edge of the screen, and sizes for the squares. Even though a stack view can take care of x and y origins, and other positioning information, the views still need to have internal sizes.

You can also ditch stack views here, and pin each of the 9 views to each other and the screen. In this case, the math you've done to draw the grid can be utilized to figure out the proper distances to pin things.

While best practice in the real world, auto layout is not required for this assignment, and your grade won't be affected by whether you use it. So you can also hard code the placements into the storyboard if layout constraints are driving you crazy.

"Turn off auto-layout for this assignment. (See the Assignment 2 write-up for a reminder of how to do this.) You should design your application for iPhone 6/7/8. It will be graded using the iPhone 8 simulator."

**Comment by chelseatroy** [comment]
Hi all!

@tracesauter — I am OK with the implementation that you have.

 Here's one thing to note: the @IBOutlets preemptively encourage having a custom GridView that contains those outlets and the logic that pertains to them. That is a good thing: we like having sets of responsibilities enclosed in objects, rather than a massive view controller.

You can still have programmatically added squares and have well-encapsulated code, so I would encourage you to make sure that that is the case with your code.

**Comment by tracesauter** [comment]
cool, thank you!
