### ISSUE TITLE
Executing Code After Gesture

### ISSUE THREAD

**Issue by tracesauter** [uchicago-mobi/MPCS51030-2019-Spring-Forum#31]
Hi,

I have my pan gesture recognizer working where the user can drag a piece and drop it on the tic tac toe board. It will snap to the appropriate tile and the Grid data structure will update accordingly so that it knows which pieces are on which tiles.

I also have a function that looks at the Grid data structure and calculates whether there is a winner. The function seems to work - I've verified it by testing various inputs and printing the outputs, but when I run it in the app it works 90% of the time and the other 10% of the time it doesn't seem to realize that there has been a winner until a turn or two later. It gets the answer right, but not in real-time the way it should. I'm not sure if anyone else is having similar problems, or if I've given enough information, but does anyone have any ideas?

Thanks!

Trace

**Comment by hbennett766** [comment]
Criteria for a thread-related bug:

✅functions work as expected via logging/testing
✅expected user-facing action happens eventually, but both late and randomly

Make sure you're presenting the info view (or whatever UI work you're doing) on the main thread. UI work must always happen with the highest priority, on thread 1.

Lmk whether that was the problem!
