### ISSUE TITLE
Assignment 5 repo link error

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#35]
The repo link posted on the Session 5 site does not appear to be working. After first directing me to allow additional permissions to GitHub Classroom, it is now giving me a 404 error. It also give me access to a GitHub Classroom dashboard, where I have the option of creating a new Classroom. 

@chelseatroy @hbennett766

**Comment by chelseatroy** [comment]
Hi Landon!

Sure thing. Let me look into this now and get it fixed pronto.

Thank you for letting us know!

**Comment by chelseatroy** [comment]
OK, Fixed!!
