### ISSUE TITLE
App Transport Security / Could not signal service 113: error

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#37]
I have run into an issue when using WKWebView to open HTTP urls. I have found two possible solutions. 

The first is to convert HTTP urls to HTTPS. This seems to work for most sites, but there still appear to be some that simply don't work as HTTPS.

The second solution is to edit the App Transport Security Settings to Allow Arbitrary Loads. So far this seems to be more effective, but my understanding is that it's not secure, and may even now be forbidden by Apple when submitting apps, at least in most cases. (I couldn't find a fully up-to-date answer on this). 

Are either of these solutions recommended/not recommended. Is there another solution I'm missing? 

Relatedly (maybe?), I am receiving a lot of  `Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service` and `Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service` errors when accessing certain sites. This errors seems to occur more frequently with sites that are not working when the above solutions are not implemented. But sometimes they also show up without any apparent effect on functionality. Research into this suggests that it may have something to do with the deallocation of WKWebView. Any more light that can be shined on this would be greatly appreciated.

**Comment by hbennett766** [comment]
Correct solution is to edit the App Transport Security Settings to Allow Arbitrary Loads in info.plist. There are no more or less security issues than accessing an `http://` web link in a browser. While not ideal, it's the only solution in iOS apart from adding domain exceptions. Not worth the trouble.

That `113` error has been popping up in `WKWebView` as long as I can remember. I _believe_ it is a known bug? As it's not affecting functionality, you can ignore it.
