### ISSUE TITLE
Apple Developer Issues

### ISSUE THREAD

**Issue by blakefleisher** [uchicago-mobi/MPCS51030-2019-Spring-Forum#4]
<img width="1481" alt="Screen Shot 2019-04-06 at 5 35 24 PM" src="https://user-images.githubusercontent.com/42075293/55676059-8452d000-5892-11e9-9fce-cff61a978fd8.png">

I'm having some problems connecting it with the apple developer account. Has anyone had similar issues. Thanks.

**Comment by hbennett766** [comment]
Note the Status error. Looks like you need a unique string for your bundle identifier. Instead of `BF.FoodTracker`, try something like `BlakeFleisher.FoodTracker` or `BlakeFleisher<some random numbers>.FoodTracker`, and then tap the "Try Again" button. Does that fix it?

**Comment by blakefleisher** [comment]
Nope, I still got the same errors.

**Comment by hbennett766** [comment]
Is the error message different than the "change to something unique" error? Once it's a unique identifier, you should at least get a different error message.

<img width="1512" alt="Screen Shot 2019-04-07 at 2 34 32 PM" src="https://user-images.githubusercontent.com/10427644/55688779-5e850400-5942-11e9-9640-417d211ace60.png">

**Comment by blakefleisher** [comment]
Actually, it has changed (I got different errors--sorry for the confusion), but it's still not working. I also probably tried it too many times.

<img width="1097" alt="Screen Shot 2019-04-07 at 3 20 41 PM" src="https://user-images.githubusercontent.com/42075293/55689350-f4bc2880-5948-11e9-9ba5-b6a7bfe4e830.png">

**Comment by hbennett766** [comment]
At least the error is descriptive. There's a limit to how many bundle IDs you can use. You'll have to use one you've already generated, if you can remember it. If you can't figure out the code signing, you should still be able to build and run on the simulator. I'll be grading this via the simulator, so it's not required to have this code signed for a device.

**Comment by blakefleisher** [comment]
Ok, for some reason it's not giving me the warning anymore, so that's good!
