### ISSUE TITLE
Final project due date

### ISSUE THREAD

**Issue by jdgarza** [uchicago-mobi/MPCS51030-2019-Spring-Forum#41]
I was wondering what the due date is. The final project page says, "Final projects will be due Wednesday, May 31, 2019 at 11:59pm."

May 31 is actually a Friday. Do we have until Wednesday, June 5 or is it Friday, May 31?

Thanks!!

**Comment by chelseatroy** [comment]
It's Friday, May 31! The idea here is that Hannah and I can get you proposal feedback between May 8 and May 10 so that you can have three full weeks to execute on the project.
