### ISSUE TITLE
Can I get a hint on the extra credit?

### ISSUE THREAD

**Issue by westminsterabi** [uchicago-mobi/MPCS51030-2019-Spring-Forum#43]
I know some professors have a policy not to do this. If so, no sweat, just thought I'd ask! 

I'm a bit stuck on how to get the article to load initially. I thought about setting it from within my MVC class, but I'm not sure how to access the DVC from within there. Same for setting the values within the DVC, I'm not sure how to get the data from the MVC.

**Comment by chelseatroy** [comment]
Hello! 

We did this in class on Wednesday :).
