### ISSUE TITLE
Final Project Repo

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#46]
I wasn't able to make class last week, so maybe I missed this, but I haven't been able to locate a link for a repo for the final project. Is there a link somewhere, or is there some other submission method I've missed?

@chelseatroy

**Comment by blakefleisher** [comment]
Did you check the issue Chelsea opened in the hw5 repo where she goes over your final project proposal? That's where the link was for me.

**Comment by chelseatroy** [comment]
Indeed.

[](https://github.com/uchicago-mobi/mpcs-51030-spring-2019-assignment-5-landonjmitchell/issues/1)

**Comment by chelseatroy** [comment]
[Indeed](https://github.com/uchicago-mobi/mpcs-51030-spring-2019-assignment-5-landonjmitchell/issues/1).
