### ISSUE TITLE
Final project due date

### ISSUE THREAD

**Issue by blakefleisher** [uchicago-mobi/MPCS51030-2019-Spring-Forum#50]
It says the final project is due Wednesday, May 31, 2019 at 11:59pm, but the 31st is actually a Friday. Is it due on that Friday? Thanks.

**Comment by jdgarza** [comment]
Check out issue #41 

It's due on Friday, May 31st.

**Comment by blakefleisher** [comment]
Thanks! Somehow I missed that.
