### ISSUE TITLE
Square images?

### ISSUE THREAD

**Issue by westminsterabi** [uchicago-mobi/MPCS51030-2019-Spring-Forum#6]
Near the end of the tutorial we are supposed to set the aspect ratio to 1:1 "so it will always be a square." Does this mean the images should automatically crop to squares? If so, I can't figure out for the life of me how to make it do that. Thanks!

**Comment by hbennett766** [comment]
The OS doesn't have the capability to crop images on its own, nor would part of the image "hide" beyond the edges of the image view to give the illusion of cropping. Depending on the other constraints you've set, you'll likely see one of two behaviors:

1. The image is stretched or compressed to be a square
2. The image keeps is original aspect ratio, and the image view molds to those dimensions

For the purpose of this assignment, either is fine.

**Comment by westminsterabi** [comment]
Cool! Thanks :)
