### ISSUE TITLE
Assignment two repo/instructions questions

### ISSUE THREAD

**Issue by landonjmitchell** [uchicago-mobi/MPCS51030-2019-Spring-Forum#7]
A few quick questions:

Will we be provided with a Repo link for assignment two as we were with the first assignment? (Or am I just not seeing it?)

The instructions state "Present a `UIAlertController` in the `.alert` style that displays the animal’s name, age and species. See image below." It doesn't appear that the image was included in the instructions. 

Unless I'm missing something, the height dimensions for the `UIScrollView` and `UILabel` seem to require overlapping the status icons at the top of the screen. Is this intentional, or should the height of one of the elements be changed?

**Comment by hbennett766** [comment]
Yes, there will be a new repo for assignment 2. Chelsea will post to the forum when that link is live.

I don't have the power to update the website, but here is a picture of an alert in the style of `.alert`:

![lee1_fig03](https://user-images.githubusercontent.com/10427644/56007945-13e7ec80-5ca0-11e9-8916-90b18ee28f02.jpg)

"Hello World!" is the title in this alert controller, and "Nice to meet you!" is the message. For your animal app, the title will be the animal's name, and the message will contain the species and the age. For example:

**Joey**
This kangaroo is 2 years old

The "OK" button will dismiss the alert.

There is a concept in iOS dev called the "safe area" of the screen. These account for margins near the edges and concerning the status icons. That's usually applicable, but not the case here. The scroll view content (labels and images and things) will never get close enough to interfere with margins. The heights are fine as is. If you want to adjust heights anyways, you're more than welcome to. Just make sure the app still functions as per the assignment write-up.
